sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react-project -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react-project npm run test -- --coverage

  deploy:
    provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    app: docker-react
    env: DockerReact-env
    region: eu-east-1
    bucket_name: elasticbeanstalk-us-east-1-054747763671
    bucket_path: docker-react
    on:
      branch: master